Refresh authentication token
Charlew/barter-it-api pull request #19
Opened 2020-05-18 07:45 UTC by Charlew

2020-05-18 14:30 UTC, Lashu requested changes

2020-05-18 14:30 UTC, Lashu commented on src/main/kotlin/barter/barter_it_api/api/user/AuthEndpoint.kt
> +    fun refreshToken(request: HttpServletRequest): String = authService.refreshToken(request.remoteUser)
Fajnie jakbyśmy przy zwracaniu tokenu zawarli wszystkie informacje z nim związane, czyli w tym przypadku token + data wygaśnięcia. Można by opakować te dwie wartości w jakąś strukturę np:
```
accesToken {
    value: String,
    expirationDate: LocalDateTime
}
```
i zwracać ją w tej funkcji, a w funkcji do logowania zamiast dwóch pól z tokenem i datą wygaśnięcia wstawić tą strukturę

2020-05-18 14:30 UTC, Lashu commented on src/main/kotlin/barter/barter_it_api/api/user/AuthEndpoint.kt
> +    @GetMapping("refresh")
Czy to czasem nie pozwala na zdobycie tokenu posiadając jedynie adres email? Wydaje mi się, że funkcja createToken w AuthService powinna wymagać hasła

2020-05-18 14:30 UTC, Lashu commented on src/test/groovy/barter/barter_it_api/api/user/UserIT.groovy
> +            freshToken instanceof String
proponuję freshToken -> refreshedToken

2020-05-18 14:30 UTC, Lashu commented on src/test/groovy/barter/barter_it_api/api/user/UserIT.groovy
> +            response.body.codes == ['User must be authenticated']
może lepiej: `codes.contains(...)`? Zapobiegnie to wywaleniu się testu jeśli w przyszłości pojawią się inne kody błędów w tym przypadku

2020-05-18 14:34 UTC, Charlew commented on src/main/kotlin/barter/barter_it_api/api/user/AuthEndpoint.kt
> +    @GetMapping("refresh")
Jest to email użytkownika, ktorego "sesja" jeszcze trwa wpw leci błąd walidacyjny. Hasło nie jest potrzebne bo i tak nie zawiera się w zaszyfrowanym tokenie. A kolizji żadnej nie będzie bo każdy email jest unikalny.

2020-05-19 15:55 UTC, Lashu approved these changes

2020-05-19 15:55 UTC, Lashu commented on src/main/kotlin/barter/barter_it_api/domain/user/AuthService.kt
>                  val tokenExpirationDate = jwtTokenProvider.getExpirationDate(token)
jwtTokenProvider.createToken() mogłoby od razu zwracać AccessToken

2020-05-19 16:33 UTC, merged